spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # 소문자 sql도 동작하지만 대문자 SQL이 공식 권장
    org.hibernate.orm.jdbc.bind: trace
